version: 2.1

# Grace to: [Teppei Sato](teppeis@gmail.com) https://github.com/teppeis-sandbox/circleci2-multiple-node-versions

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Install gulp cli
          command: npm i -D gulp-cli
      - run:
          name: Lint
          command: npx gulp lint
      - run:
          name: Build
          command: npx gulp lint
      # - run:
      #     name: Test
      #     command: npx gulp test
      - save-npm-cache
  test-nodejs-v6:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install gulp cli
          command: npm install -D gulp-cli
      - run:
          name: Lint
          command: npx gulp lint
      - run:
          name: Build
          command: npx gulp lint
      # - run:
      #     name: Test
      #     command: npx gulp test
      - save-npm-lock
      - save-npm-cache
  save-npm-lock:
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  save-npm-cache:
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/_cacache

# Obtain versions with: `curl -sSL https://registry.hub.docker.com/v1/repositories/circleci/node/tags | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n'  | awk -F: '{print $3}' | sort | grep -e "^11."`

jobs:
  node-v6:
    docker:
      # - image: circleci/node:6.16.0-browsers
      - image: circleci/node:6-stretch-browsers
    steps:
      - test-nodejs-v6
  node-v8:
    docker:
      # - image: circleci/node:8.9.4-browsers
      - image: circleci/node:8-stretch-browsers
    steps:
      - test-nodejs
  node-v10:
    docker:
      # - image: circleci/node:10.9.0-browsers
      - image: circleci/node:10-stretch-browsers
    steps:
      - test-nodejs
  node-v11:
    docker:
      # - image: circleci/node:11.9-browsers
      - image: circleci/node:11-stretch-browsers
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v6
      - node-v8
      - node-v10
      - node-v11
